# general configuration
n_samples: 1

generate_input: false
geometry_only: false

input_dir: "gprmax_input_files/generated/"
tmp_dir: "gprmax_tmp_files/"
output_dir: "gprmax_output_files/"

# simulation configuration
n_ascans: 2
domain: [1.5, 1.70, 0.002]
spatial_resolution: [0.002, 0.002, 0.002]
time_window: 2.5e-08

source_waveform: "ricker"
source_amplitude: 1
source_central_frequency: 1000000000
source_position: [0.2, 1.50, 0.001]
receiver_position: [0.35, 1.50, 0.001]
step_size: [0.02, 0, 0]

fractal_dimension: 1.5
pep_soil_number: 15

materials: {
  ballast: [6.5, 0, 1, 0],
  concrete: [8, 0.01, 1, 0],
  gravel: [5, 0, 1, 0],
  wood: [2, 0.01, 1, 0],
  steel: [1, inf, 1, 0], # perfect electric conductor (pec)
  asphalt: [8, 0.01, 1, 0],
  # peplinsky soils: the last two values are min and max water content across samples, 
  # the actual values will be sampled during dataset creation based on general 
  # water content of the sample.
  fouling: [0, 1, 3, 2.66, 0.03, 0.18],
  PSS: [0.9, 0.1, 2, 2.66, 0.03, 0.18],
  subsoil: [1, 0, 2, 2.66, 0.03, 0.18],
}

antenna_sleeper_distance: 0.465

# interval in which to sample the layer sizes, 
# asphalt only used for AC rail
layer_sizes: {
  ballast: [0.3, 0.5],
  asphalt: [0.05, 0.1],
  PSS: [0.2, 0.4]
}
# roughness of the layers
layer_roughness: {
  top_fouling: 0.02,
  fouling_asphalt: 0.02,
  asphalt_pss: 0.03,
  pss_subsoil: 0.05
}

# sleepers
sleepers_separation: 0.65
sleepers_material: ["all"]
sleepers_size: [0.17, 0.10, 0.002]

# fouling and water content
fouling_prob: 0.5
max_fouling_percentage: 1
fouling_water_range: [0.03, 0.15]
pss_water_range: [0.03, 0.15]

# wavefield snapshots
snapshot_times: [1.0e-09, 2.0e-09, 3.0e-09, 4.0e-09, 5.0e-09, 6.0e-09, 7.0e-09, 8.0e-09, 9.0e-09, 1.0e-08, 1.1e-08, 1.2e-08, 1.3e-08, 1.4e-08, 1.5e-08, 1.6e-08, 1.7e-08, 1.8e-08, 1.9e-08, 2.0e-08, 2.1e-08, 2.2e-08, 2.3e-08, 2.4e-08]