# general configuration
n_samples: 2

generate_input: false
geometry_only: false

input_dir: "gprmax_input_files/generated/"
tmp_dir: "gprmax_tmp_dir/"
output_dir: "gprmax_output_files/"

# simulation configuration
n_ascans: 2
domain: [1.5, 1.73, 0.002]
spatial_resolution: [0.002, 0.002, 0.002]
time_window: 2.5e-08

source_waveform: "ricker"
source_amplitude: 1
source_central_frequency: 1000000000
source_position: [0.2, 1.53, 0.001]
receiver_position: [0.35, 1.53, 0.001]
step_size: [0.02, 0, 0]

fractal_dimension: 1.5
pep_soil_number: 5

materials: {
  ballast: [6.5, 0, 1, 0],
  concrete: [8, 0.01, 1, 0],
  pss: [0.9, 0.1, 2, 2.66, 0.02, 0.03],
  gravel: [5, 0, 1, 0],
  fouling: [0.9, 0.1, 2, 2.66, 0.02, 0.03],
  wood: [2, 0.01, 1, 0],
  steel: [1, 0, 1000, 0],
  asphalt: [8, 0.01, 1, 0],
}

layer_sizes: [0.15, 0.30, 0.55, 0.70]
layer_deviations: [0.03, 0.03, 0.05, 0.05]

# sleepers
sleepers_separation: 0.65
sleepers_material: ["all"]
sleepers_size: [0.17, 0.10, 0.002]

# fouling and water content
max_fouling_level: 0.15
max_fouling_water: 0.15
max_pss_water: 0.15

# wavefield snapshots
snapshot_times: [0.5e-9, 1.0e-9, 1.5e-9, 2.0e-9, 2.5e-9, 3.0e-9, 3.5e-9, 4.0e-9, 4.5e-9, 5.0e-9]